races = [
        {"finishers": ['Chocosura', 'dipwood', 'Pseudoarc', 'Xelpher', 'lordbatsy', 'CivilChev', 'AzureCale', 'Janus', 'akuheish', 'kalarse', 'Kyuketsuki', 'Theferrell', 'IBKarma'],
         "forfeits": ['Tekenu', 'Anskiy'],
         "nonparticipants": ['Lingerer the Lingerer', 'CrisR0', 'Kennori']},
        {"finishers": ['Chocosura', 'Xelpher', 'dipwood', 'Janus', 'kalarse', 'CivilChev', 'Kyuketsuki', 'AzureCale', 'akuheish', 'Theferrell', 'lordbatsy', 'IBKarma'],
         "forfeits": ['Anskiy', 'proccy'],
         "nonparticipants": ['Lingerer the Lingerer', 'CrisR0', 'Kennori', 'Tekenu', 'Pseudoarc']},
        {"finishers": ['Chocosura', 'Xelpher', 'Janus', 'dipwood', 'Pseudoarc', 'Anskiy', 'Theferrell', 'lordbatsy', 'Kyuketsuki', 'akuheish', 'Tekenu', 'AzureCale', 'kalarse', 'CivilChev', 'smercjd'], "nonparticipants": ['proccy', 'IBKarma'], "forfeits": []},
        {"finishers": ['Xelpher', 'Chocosura', 'dipwood', 'lordbatsy', 'Janus', 'CivilChev', 'kalarse', 'Kyuketsuki', 'Anskiy', 'akuheish', 'Tekenu', 'AzureCale', 'MrScruffNinjaTuna'],
         "forfeits": ['Theferrell', 'smercjd', 'IBKarma', 'proccy'],
         "nonparticipants": []},
        {"finishers": ['dipwood', 'Xelpher', 'kalarse', 'Chocosura', 'AzureCale', 'Korenth', 'Tekenu', 'Theferrell', 'Kyuketsuki', 'CivilChev'],
         "forfeits": ["smercjd", "Anskiy", "akuheish", "lordbatsy"],
         "nonparticipants": []},
        {"finishers": {1: 'AzureCale', 2: ['Xelpher', 'Chocosura'], 4: 'Pseudoarc', 5: 'kalarse', 6: 'dipwood', 7: 'akuheish', 8: 'Kyuketsuki', 9: 'Theferrell', 10: 'Tekenu'},
         "forfeits": [],
         "nonparticipants": []},
        {"finishers": ["dipwood", "Xelpher", "Pseudoarc", "Chocosura", "AzureCale", "kalarse", "lordbatsy", "Kyuketsuki", "akuheish", "Tekenu", "Theferrell"],
         "forfeits": [],
         "nonparticipants": []}
        ]
